#!/usr/bin/env bash

# Unsteady-diffusion ST-DDROM launcher (all-at-once/window-marching/compare).
#
# - Builds solvers/diff/Makefile_ST.
# - Partitions only the ordinary spatial mesh into MPI domains.
# - Does NOT use meshgen_ST, st_meta.dat, owner.dat, or the ST partition
#   postprocessor.
# - Runs dG(0) reduced solver in all-at-once, window-marching, or compare mode.
#
# Expected Makefile_ST executable (override with ST_DDROM_EXECUTABLE):
#   hlpod_diff_st_ddrom

if [[ -z "${BASH_VERSION:-}" ]]; then
    exec /usr/bin/env bash "$0" "$@"
fi

set -euo pipefail

usage() {
    cat >&2 <<'USAGE'
Usage:
  execution_ST_DDROM_MPI.sh <e> <ep> <nm> <nd> <np> <pa> <st>

Arguments:
  e   : number of hexahedral elements in each spatial direction
  ep  : domain length in each spatial direction
  nm  : result-directory tag / legacy ROM option
  nd  : legacy domain option (not used for spatial partitioning)
  np  : MPI process count and spatial partition count
  pa  : legacy POD option; also used as the default max POD modes when pa > 0
  st  : legacy solver option passed through to the executable

Example:
  bash shell/diff/execution_ST_DDROM_MPI.sh 20 1.0 10 4 4 8 0

Important environment variables:
  ST_PROJECT_ROOT                 : project root (rom_hlpod_ddecm_dev)
  ST_DDROM_EXECUTABLE             : executable created by Makefile_ST
                                    (default: hlpod_diff_st_ddrom)
  ST_FOM_REBUILD=0|1              : rebuild Makefile_ST target (default: 1)
  ST_CLEAN_RESULT=0|1             : clean the case before preparation
                                    (default: 1 for full/offline, 0 for online)
  ST_PREPARE_ONLY=0|1             : stop after mesh partitioning (default: 0)
  ST_RESULT_DIR=<path>            : override result directory

  DIFF_ST_DDROM_MODE=full|offline|online
                                    (default: full)
  DIFF_ST_DDROM_SOLVER=all-at-once|window-marching|compare
                                    (default: all-at-once)
                                    compare runs both reduced solvers and
                                    reports coefficient/residual/timing differences
  DIFF_ST_DDROM_SLABS_PER_WINDOW  : slabs per time window (default: 4)
  DIFF_ST_DDROM_TRAINING_WINDOWS  : number of training windows
                                    (default: all windows)
  DIFF_ST_DDROM_MAX_MODES         : max POD modes/rank
                                    (default: pa if pa>0, otherwise 10)
  DIFF_ST_DDROM_POD_ENERGY        : POD retained energy (default: 0.999999)
  DIFF_ST_DDROM_WRITE_OUTPUT=0|1  : write reconstructed VTK output (default: 1)
  DIFF_ST_DDROM_BASIS_SUBDIR      : basis directory (default: stddrom_basis)
  DIFF_ST_DDROM_OPERATOR_SUBDIR   : operator directory
                                    (default: stddrom_operators)

The default cond.dat generated by this launcher is:
  dt          = 0.01
  finish_time = 1.0
so total_steps=100.  DIFF_ST_DDROM_SLABS_PER_WINDOW must divide 100 unless
cond.dat is replaced with another consistent case.
USAGE
}

if [[ "$#" -ne 7 ]]; then
    usage
    exit 2
fi

e="$1"
ep="$2"
nm="$3"
nd="$4"
np="$5"
pa="$6"
st="$7"

for pair in "e:$e" "nm:$nm" "nd:$nd" "np:$np" "pa:$pa"; do
    name="${pair%%:*}"
    value="${pair#*:}"
    if ! [[ "$value" =~ ^[0-9]+$ ]]; then
        echo "ERROR: ${name} must be a nonnegative integer: ${value}" >&2
        exit 2
    fi
done

if (( e <= 0 || np <= 0 )); then
    echo "ERROR: e and np must be positive." >&2
    exit 2
fi

if ! [[ "$ep" =~ ^([0-9]+([.][0-9]*)?|[.][0-9]+)([eE][+-]?[0-9]+)?$ ]]; then
    echo "ERROR: ep must be a positive number: ${ep}" >&2
    exit 2
fi

# Reject zero without requiring bc/awk/python.
if [[ "$ep" =~ ^0*([.]0*)?([eE][+-]?[0-9]+)?$ ]]; then
    echo "ERROR: ep must be greater than zero: ${ep}" >&2
    exit 2
fi

script_path="${BASH_SOURCE[0]:-$0}"
script_dir="$(cd "$(dirname "$script_path")" && pwd)"

find_project_root() {
    local candidate
    for candidate in \
        "${ST_PROJECT_ROOT:-}" \
        "$(pwd)" \
        "${script_dir}/../.." \
        "${script_dir}/../../.." \
        "${script_dir}/../../../.."; do
        [[ -n "$candidate" ]] || continue
        candidate="$(cd "$candidate" 2>/dev/null && pwd || true)"
        [[ -n "$candidate" ]] || continue
        if [[ -f "$candidate/shell/install.sh" && \
              -f "$candidate/solvers/diff/Makefile_ST" ]]; then
            printf '%s\n' "$candidate"
            return 0
        fi
    done
    return 1
}

project_root="$(find_project_root || true)"
if [[ -z "$project_root" ]]; then
    echo "ERROR: project root was not found." >&2
    echo "Set ST_PROJECT_ROOT to rom_hlpod_ddecm_dev." >&2
    exit 1
fi

# shellcheck source=/dev/null
source "$project_root/shell/install.sh"

solver_dir="$project_root/solvers/diff"
solver_exe="${ST_DDROM_EXECUTABLE:-hlpod_diff_st_ddrom}"
result_dir="${ST_RESULT_DIR:-$project_root/result_diff/${nm}-${np}-${nd}}"

mode="${DIFF_ST_DDROM_MODE:-full}"
case "$mode" in
    full|offline|online) ;;
    *)
        echo "ERROR: DIFF_ST_DDROM_MODE must be full, offline, or online: $mode" >&2
        exit 2
        ;;
esac

solver_strategy="${DIFF_ST_DDROM_SOLVER:-all-at-once}"
case "$solver_strategy" in
    all-at-once|aoa) solver_strategy="all-at-once" ;;
    window-marching|marching) solver_strategy="window-marching" ;;
    compare|both) solver_strategy="compare" ;;
    *)
        echo "ERROR: DIFF_ST_DDROM_SOLVER must be all-at-once, window-marching, or compare: $solver_strategy" >&2
        exit 2
        ;;
esac

rebuild_solver="${ST_FOM_REBUILD:-1}"
prepare_only="${ST_PREPARE_ONLY:-0}"
omp_threads="${OMP_NUM_THREADS:-1}"

if [[ -n "${ST_CLEAN_RESULT+x}" ]]; then
    clean_result="$ST_CLEAN_RESULT"
elif [[ "$mode" == "online" ]]; then
    clean_result=0
else
    clean_result=1
fi

for pair in \
    "ST_FOM_REBUILD:$rebuild_solver" \
    "ST_CLEAN_RESULT:$clean_result" \
    "ST_PREPARE_ONLY:$prepare_only"; do
    name="${pair%%:*}"
    value="${pair#*:}"
    if [[ "$value" != "0" && "$value" != "1" ]]; then
        echo "ERROR: ${name} must be 0 or 1: ${value}" >&2
        exit 2
    fi
done

if [[ "$mode" == "online" && "$clean_result" -eq 1 ]]; then
    echo "ERROR: online mode cannot be used with ST_CLEAN_RESULT=1." >&2
    echo "The offline basis/operators would be deleted. Use ST_CLEAN_RESULT=0." >&2
    exit 2
fi

slabs_per_window="${DIFF_ST_DDROM_SLABS_PER_WINDOW:-4}"
pod_energy="${DIFF_ST_DDROM_POD_ENERGY:-0.999999}"
write_output="${DIFF_ST_DDROM_WRITE_OUTPUT:-1}"
basis_subdir="${DIFF_ST_DDROM_BASIS_SUBDIR:-stddrom_basis}"
operator_subdir="${DIFF_ST_DDROM_OPERATOR_SUBDIR:-stddrom_operators}"

if [[ -n "${DIFF_ST_DDROM_MAX_MODES+x}" ]]; then
    max_modes="$DIFF_ST_DDROM_MAX_MODES"
elif (( pa > 0 )); then
    max_modes="$pa"
else
    max_modes=10
fi

if ! [[ "$slabs_per_window" =~ ^[1-9][0-9]*$ ]]; then
    echo "ERROR: DIFF_ST_DDROM_SLABS_PER_WINDOW must be a positive integer: $slabs_per_window" >&2
    exit 2
fi
if ! [[ "$max_modes" =~ ^[1-9][0-9]*$ ]]; then
    echo "ERROR: DIFF_ST_DDROM_MAX_MODES must be a positive integer: $max_modes" >&2
    exit 2
fi
if [[ "$write_output" != "0" && "$write_output" != "1" ]]; then
    echo "ERROR: DIFF_ST_DDROM_WRITE_OUTPUT must be 0 or 1: $write_output" >&2
    exit 2
fi

run_label="${ST_DDROM_RUN_LABEL:-stddrom_${mode}_${solver_strategy}_np${np}}"

thermal_root="${TEST_THERMAL_ROOT:-$project_root/../test_thermal}"
cmd2cond="${CMD2COND:-$thermal_root/bin/cmd2cond}"
meshgen_hex="${MESHGEN_HEX:-$thermal_root/bin/meshgen_hex}"
surf_dbc_all="${SURF_DBC_ALL:-$thermal_root/bin/surf_dbc_all}"
gedatsu_bin="${GEDATSU_BIN:-$thermal_root/submodule/monolis/submodule/gedatsu/bin}"
mesh2graph="${GEDATSU_MESH2GRAPH:-$gedatsu_bin/gedatsu_simple_mesh2graph_convertor}"
mesh_partitioner="${GEDATSU_MESH_PARTITIONER:-$gedatsu_bin/gedatsu_simple_mesh_partitioner}"
graph_partitioner="${GEDATSU_GRAPH_PARTITIONER:-$gedatsu_bin/gedatsu_nodal_graph_partitioner}"
bc_partitioner="${GEDATSU_BC_PARTITIONER:-$gedatsu_bin/gedatsu_bc_partitioner_R}"

for tool in \
    "$cmd2cond" \
    "$meshgen_hex" \
    "$surf_dbc_all" \
    "$mesh2graph" \
    "$mesh_partitioner" \
    "$graph_partitioner" \
    "$bc_partitioner"; do
    if [[ ! -x "$tool" ]]; then
        echo "ERROR: required executable was not found: $tool" >&2
        exit 1
    fi
done

# ---------------------------------------------------------------------------
# Build the all-at-once ST-DDROM solver from solvers/diff/Makefile_ST.
# ---------------------------------------------------------------------------

if [[ "$rebuild_solver" -eq 1 || ! -x "$solver_dir/$solver_exe" ]]; then
    echo "Building diffusion all-at-once ST-DDROM with Makefile_ST..."
    (
        cd "$solver_dir"
        make -f Makefile_ST clean
        make -f Makefile_ST
    )

    if [[ ! -x "$solver_dir/$solver_exe" ]]; then
        echo "ERROR: build did not create $solver_dir/$solver_exe" >&2
        echo "If Makefile_ST uses another target name, set ST_DDROM_EXECUTABLE." >&2
        exit 1
    fi
fi

# ---------------------------------------------------------------------------
# Prepare or validate the ordinary spatial case.
# ---------------------------------------------------------------------------

if [[ "$mode" == "online" ]]; then
    if [[ ! -d "$result_dir" ]]; then
        echo "ERROR: online case directory does not exist: $result_dir" >&2
        echo "Run DIFF_ST_DDROM_MODE=offline or full first." >&2
        exit 1
    fi
else
    if [[ "$clean_result" -eq 1 ]]; then
        rm -rf "$result_dir"
    fi
    mkdir -p \
        "$result_dir" \
        "$result_dir/fem_solver_prm" \
        "$result_dir/calctime"
fi

# For online mode mkdir -p is intentionally harmless only after confirming the
# case exists.  It also repairs missing auxiliary output directories.
mkdir -p "$result_dir/fem_solver_prm" "$result_dir/calctime"
cp -f "$solver_dir/$solver_exe" "$result_dir/$solver_exe"

cd "$result_dir"

if [[ "$mode" == "online" ]]; then
    for required in cond.dat node.dat elem.dat graph.dat D_bc.dat; do
        if [[ ! -f "$required" ]]; then
            echo "ERROR: online mode requires existing case file: $result_dir/$required" >&2
            exit 1
        fi
    done
else
    if [[ "$clean_result" -eq 1 || ! -f cond.dat ]]; then
        rm -f cond.dat rom_cond.dat

        # Kept for compatibility with the existing diffusion workflow.  The
        # new ST-DDROM main reads cond.dat directly; rom_cond.dat is not needed
        # by the all-at-once solve itself.
        "$cmd2cond" \
            "#snapshot_interval" int 1 1 \
            "#rom_finish_time" double 1 4.0 \
            "#rom_output_interval" int 1 1
        mv cond.dat rom_cond.dat

        "$cmd2cond" \
            "#time_spacing" double 1 0.01 \
            "#output_interval" int 1 1 \
            "#finish_time" double 1 1.0
    fi

    if [[ "$clean_result" -eq 1 || ! -f node.dat || ! -f elem.dat || ! -f D_bc.dat ]]; then
        "$meshgen_hex" "$e" "$e" "$e" "$ep" "$ep" "$ep"
        "$surf_dbc_all" 1 1.0
    fi

    if [[ "$clean_result" -eq 1 || ! -f graph.dat ]]; then
        "$mesh2graph" -i elem.dat -o graph.dat
    fi
fi

# Recreate partition data whenever necessary.  online mode never silently
# regenerates partitions because its saved basis/operator files are tied to the
# exact MPI decomposition used by the offline run.
partition_ready=1
for ((rank=0; rank<np; rank++)); do
    for required in \
        "parted.0/node.dat.${rank}" \
        "parted.0/elem.dat.${rank}" \
        "parted.0/graph.dat.${rank}" \
        "parted.0/D_bc.dat.${rank}"; do
        [[ -f "$required" ]] || partition_ready=0
    done
done

if [[ "$partition_ready" -eq 0 ]]; then
    if [[ "$mode" == "online" ]]; then
        echo "ERROR: online mode requires the original ${np}-rank spatial partition." >&2
        echo "Missing files under: $result_dir/parted.0" >&2
        exit 1
    fi

    rm -rf parted.0
    echo "Partitioning ordinary spatial mesh into ${np} domains..."
    "$mesh_partitioner" -n "$np"
    "$graph_partitioner" -n "$np" -i graph.dat
    "$bc_partitioner" -n "$np" -i D_bc.dat -ig node.dat
fi

for ((rank=0; rank<np; rank++)); do
    for required in \
        "parted.0/node.dat.${rank}" \
        "parted.0/elem.dat.${rank}" \
        "parted.0/graph.dat.${rank}" \
        "parted.0/D_bc.dat.${rank}"; do
        if [[ ! -f "$required" ]]; then
            echo "ERROR: missing spatial partition file: $result_dir/$required" >&2
            exit 1
        fi
    done
done

# In online mode, verify the rank-local offline artifacts before mpirun.  Their
# file headers perform stricter consistency checks again inside the C solver.
if [[ "$mode" == "online" ]]; then
    for ((rank=0; rank<np; rank++)); do
        rank6="$(printf '%06d' "$rank")"
        basis_file="$basis_subdir/stddrom_basis_rank_${rank6}.bin"
        operator_file="$operator_subdir/stddrom_operators_rank_${rank6}.bin"
        for required in "$basis_file" "$operator_file"; do
            if [[ ! -f "$required" ]]; then
                echo "ERROR: online ST-DDROM artifact is missing: $result_dir/$required" >&2
                echo "Run an offline/full solve first with the same np/windows/slabs-per-window." >&2
                exit 1
            fi
        done
    done
fi

# Export runtime controls before mpirun so every MPI rank inherits them.
export OMP_NUM_THREADS="$omp_threads"
export DIFF_ST_DDROM_MODE="$mode"
export DIFF_ST_DDROM_SOLVER="$solver_strategy"
export DIFF_ST_DDROM_SLABS_PER_WINDOW="$slabs_per_window"
export DIFF_ST_DDROM_MAX_MODES="$max_modes"
export DIFF_ST_DDROM_POD_ENERGY="$pod_energy"
export DIFF_ST_DDROM_WRITE_OUTPUT="$write_output"
export DIFF_ST_DDROM_BASIS_SUBDIR="$basis_subdir"
export DIFF_ST_DDROM_OPERATOR_SUBDIR="$operator_subdir"

# Preserve optional controls only when the caller provided them.
if [[ -n "${DIFF_ST_DDROM_TRAINING_WINDOWS:-}" ]]; then
    export DIFF_ST_DDROM_TRAINING_WINDOWS
fi
if [[ -n "${DIFF_ST_DDROM_LINEAR_MAX_ITER:-}" ]]; then
    export DIFF_ST_DDROM_LINEAR_MAX_ITER
fi
if [[ -n "${DIFF_ST_DDROM_LINEAR_EPSILON:-}" ]]; then
    export DIFF_ST_DDROM_LINEAR_EPSILON
fi

echo
echo "Diffusion all-at-once ST-DDROM preparation completed."
echo "  project root     : $project_root"
echo "  solver           : $solver_dir/Makefile_ST -> $solver_exe"
echo "  case directory   : $result_dir"
echo "  partition data   : $result_dir/parted.0"
echo "  MPI domains      : $np"
echo "  mode             : $mode"
echo "  solver strategy  : $DIFF_ST_DDROM_SOLVER"
echo "  time scheme      : dG(0)"
echo "  slabs/window     : $DIFF_ST_DDROM_SLABS_PER_WINDOW"
echo "  max modes/rank   : $DIFF_ST_DDROM_MAX_MODES"
echo "  POD energy       : $DIFF_ST_DDROM_POD_ENERGY"
echo "  manufactured rank: ${DIFF_MANUFACTURED_RANK:-0}"
if [[ "${DIFF_MANUFACTURED_RANK:-0}" != "0" ]]; then
    echo "  manufactured kappa: ${DIFF_MANUFACTURED_KAPPA:-1.0}"
    echo "  manufactured amp  : ${DIFF_MANUFACTURED_AMPLITUDE:-1.0}"
fi
echo "  training windows : ${DIFF_ST_DDROM_TRAINING_WINDOWS:-all}"
echo "  basis directory  : $basis_subdir"
echo "  operator dir     : $operator_subdir"
echo "  write VTK        : $DIFF_ST_DDROM_WRITE_OUTPUT"
echo "  no st_meta.dat / owner.dat / ST postprocessor is used"

if [[ "$prepare_only" -eq 1 ]]; then
    echo "ST_PREPARE_ONLY=1: stopping before mpirun."
    exit 0
fi

# ---------------------------------------------------------------------------
# Run the spatially partitioned, all-window reduced solve.
# ---------------------------------------------------------------------------

cat > gdb_cmd <<GDBEOF
set env OMP_NUM_THREADS $OMP_NUM_THREADS
set env DIFF_ST_DDROM_MODE $DIFF_ST_DDROM_MODE
set env DIFF_ST_DDROM_SOLVER $DIFF_ST_DDROM_SOLVER
set env DIFF_ST_DDROM_SLABS_PER_WINDOW $DIFF_ST_DDROM_SLABS_PER_WINDOW
set env DIFF_ST_DDROM_MAX_MODES $DIFF_ST_DDROM_MAX_MODES
set env DIFF_ST_DDROM_POD_ENERGY $DIFF_ST_DDROM_POD_ENERGY
set env DIFF_ST_DDROM_WRITE_OUTPUT $DIFF_ST_DDROM_WRITE_OUTPUT
set env DIFF_ST_DDROM_BASIS_SUBDIR $DIFF_ST_DDROM_BASIS_SUBDIR
set env DIFF_ST_DDROM_OPERATOR_SUBDIR $DIFF_ST_DDROM_OPERATOR_SUBDIR
run ./ -nd ${nd} -nm ${nm} -pa ${pa} -st ${st}
backtrace
quit
GDBEOF

log_file="${run_label}.log"
rm -f "$log_file"

command=(
    mpirun
    -np "$np"
    "./$solver_exe"
    ./
    -nd "$nd"
    -nm "$nm"
    -pa "$pa"
    -st "$st"
)

printf 'Command:'
printf ' %q' "${command[@]}"
printf '\n'

start_seconds=$SECONDS
if ! "${command[@]}" 2>&1 | tee "$log_file"; then
    echo "ERROR: ST-DDROM executable returned a nonzero status." >&2
    echo "Check: $result_dir/$log_file" >&2
    exit 1
fi
elapsed_seconds=$((SECONDS - start_seconds))

if [[ "$mode" == "offline" ]]; then
    success_pattern='offline projection complete'
else
    success_pattern='diffusion ST-DDROM completed:'
fi

if ! grep -q "$success_pattern" "$log_file"; then
    echo "ERROR: solver exited without the expected completion marker:" >&2
    echo "  $success_pattern" >&2
    echo "Check: $result_dir/$log_file" >&2
    exit 1
fi

echo
if [[ "$mode" == "offline" ]]; then
    echo "Diffusion ST-DDROM offline stage completed."
    grep 'offline projection complete' "$log_file" | tail -n 1 || true
    echo "Basis     : $result_dir/$basis_subdir"
    echo "Operators : $result_dir/$operator_subdir"
else
    echo "Diffusion ST-DDROM run completed ($DIFF_ST_DDROM_SOLVER)."
    grep 'all-at-once algebraic residual' "$log_file" | tail -n 1 || true
    grep 'window-marching reduced residual' "$log_file" | tail -n 1 || true
    grep 'coefficient relative difference' "$log_file" | tail -n 1 || true
    echo
    grep -A20 'ST-DDROM timing summary' "$log_file" | tail -n 22 || true
    grep 'diffusion ST-DDROM completed:' "$log_file" | tail -n 1 || true
    if [[ -f stddrom_l2_error.csv ]]; then
        echo "L2 error  : $result_dir/stddrom_l2_error.csv"
    fi
    if [[ -f stddrom_timing.csv ]]; then
        echo "Timing    : $result_dir/stddrom_timing.csv"
    fi
    echo "Coefficients: $result_dir/stddrom_coefficients.csv.rank_XXXXXX"
fi

echo "Run log   : $result_dir/$log_file"
echo "Wall time : ${elapsed_seconds} s"
