#!/usr/bin/env python3
import math


def time_element(degree):
    if degree == 1:
        s = 1.0 / math.sqrt(3.0)
        tau = [0.5*(1-s), 0.5*(1+s)]
        w = [0.5, 0.5]
        psi = [[1-t for t in tau], tau[:]]
        dpsi = [[-1.0, -1.0], [1.0, 1.0]]
        Mt = [[1/3,1/6],[1/6,1/3]]
        Dt = [[-1/2,1/2],[-1/2,1/2]]
        em = [1.0,0.0]
        ep = [0.0,1.0]
    elif degree == 2:
        s = math.sqrt(3.0/5.0)
        tau = [0.5*(1-s), 0.5, 0.5*(1+s)]
        w = [5/18,4/9,5/18]
        psi = [
            [2*t*t-3*t+1 for t in tau],
            [-4*t*t+4*t for t in tau],
            [2*t*t-t for t in tau],
        ]
        dpsi = [
            [4*t-3 for t in tau],
            [-8*t+4 for t in tau],
            [4*t-1 for t in tau],
        ]
        Mt = [[2/15,1/15,-1/30],[1/15,8/15,1/15],[-1/30,1/15,2/15]]
        Dt = [[-1/2,2/3,-1/6],[-2/3,0,2/3],[1/6,-2/3,1/2]]
        em = [1,0,0]
        ep = [0,0,1]
    else:
        raise ValueError(degree)
    return tau,w,psi,dpsi,Mt,Dt,em,ep

for degree in (1,2):
    tau,w,psi,dpsi,Mt,Dt,em,ep = time_element(degree)
    nt=len(psi)
    # Scalar model R=(u-u_old)/dt+k u, dt=0.37,k=2.3.
    dt=0.37
    k=2.3
    Jcur=1/dt+k
    Jold=-1/dt
    A=[[0.0]*nt for _ in range(nt)]
    for a in range(nt):
        for b in range(nt):
            for q in range(len(w)):
                A[a][b] += w[q]*psi[a][q]*(psi[b][q]*Jcur + (psi[b][q]-dpsi[b][q])*Jold)
            A[a][b] += -em[a]*em[b]*Jold
    exact=[[Dt[a][b]/dt + em[a]*em[b]/dt + Mt[a][b]*k for b in range(nt)] for a in range(nt)]
    err=max(abs(A[a][b]-exact[a][b]) for a in range(nt) for b in range(nt))
    # Previous-slab block generated by +e- e+ Jold.
    B=[[em[a]*ep[b]*Jold for b in range(nt)] for a in range(nt)]
    exactB=[[-em[a]*ep[b]/dt for b in range(nt)] for a in range(nt)]
    errB=max(abs(B[a][b]-exactB[a][b]) for a in range(nt) for b in range(nt))
    print(f'dG({degree}) current-block identity error : {err:.16e}')
    print(f'dG({degree}) previous-block identity error: {errB:.16e}')
    if err > 5e-14 or errB > 5e-14:
        raise SystemExit(1)
print('STATUS: temporal algebra MATCH')
