#!/usr/bin/env bash
set -Eeuo pipefail

export FLUID_ST_PRESSURE_GAUGE="${FLUID_ST_PRESSURE_GAUGE:-1}"
export FLUID_ST_JOLD_MODE="${FLUID_ST_JOLD_MODE:-fd}"
export FLUID_ST_WINDOW_LINEAR_SOLVER="${FLUID_ST_WINDOW_LINEAR_SOLVER:-bicgsafe}"
export FLUID_ST_WINDOW_LINEAR_EPSILON="${FLUID_ST_WINDOW_LINEAR_EPSILON:-1.0e-8}"
export FLUID_ST_WINDOW_LINEAR_MAX_ITER="${FLUID_ST_WINDOW_LINEAR_MAX_ITER:-10000}"

exec bash "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/run_ST_GEDATSU_MPI.sh" "$@"
