#!/usr/bin/env python3
"""Consistency checks for node/tetra/prism/graph/BC mixed mesh files."""
from __future__ import annotations

import argparse
from pathlib import Path


def read_nodes(path: Path):
    with path.open(encoding="utf-8") as f:
        n = int(f.readline().split()[0])
        xyz = [tuple(map(float, line.split()[:3])) for line in f if line.strip()]
    assert len(xyz) == n, (path, n, len(xyz))
    return xyz


def read_elem(path: Path, nen_expected: int):
    with path.open(encoding="utf-8") as f:
        h = f.readline().split(); ne, nen = map(int, h[:2])
        assert nen == nen_expected, (path, nen)
        e = [list(map(int, x.split())) for x in f if x.strip()]
    assert len(e) == ne, (path, ne, len(e))
    return e


def read_graph(path: Path, nnode: int):
    with path.open(encoding="utf-8") as f:
        assert int(f.readline()) == nnode
        adj = [set() for _ in range(nnode)]
        seen = set()
        for raw in f:
            if not raw.strip(): continue
            p = list(map(int, raw.split()))
            i, n = p[0], p[1]
            vals = p[2:]
            assert len(vals) == n, (i, n, len(vals))
            assert 0 <= i < nnode and i not in seen
            seen.add(i); adj[i] = set(vals)
    assert len(seen) == nnode, (len(seen), nnode)
    return adj


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("mesh_dir", type=Path)
    ap.add_argument("--diameter", type=float, default=1.0)
    ap.add_argument("--check-cylinder-radius", action="store_true")
    args = ap.parse_args()
    d = args.mesh_dir
    xyz = read_nodes(d / "node.dat")
    nnode = len(xyz)
    tet = read_elem(d / "elem_tet.dat", 4)
    pri = read_elem(d / "elem_prism.dat", 6)
    adj = read_graph(d / "graph.dat", nnode)

    for label, elems in (("tet", tet), ("prism", pri)):
        for ie, e in enumerate(elems):
            assert all(0 <= n < nnode for n in e), (label, ie, e)
            for i in e:
                for j in e:
                    if i != j:
                        assert j in adj[i], f"graph missing edge {i}-{j} from {label} element {ie}"
    for i, ngh in enumerate(adj):
        assert i not in ngh, f"self edge at node {i}"
        for j in ngh:
            assert i in adj[j], f"graph is not symmetric: {i}-{j}"

    bc = d / "D_bc_v.dat"
    if bc.exists():
        with bc.open(encoding="utf-8") as f:
            h = f.readline().split(); nbc, bs = map(int, h[:2]); assert bs == 3
            rows = [x.split() for x in f if x.strip()]
        assert len(rows) == nbc
        for r in rows:
            n, dof = int(r[0]), int(r[1])
            assert 0 <= n < nnode and 0 <= dof < 3


    # Geometry sanity check: the Physical Cylinder_wall generated by the radial
    # boundary-layer extrusion should lie at r=d/2. This catches an accidentally
    # reversed topological boundary-layer normal (which would extrude outward).
    wall_ids = d / "Cylinder_wall_node_ids.dat"
    if args.check_cylinder_radius and wall_ids.exists():
        with wall_ids.open(encoding="utf-8") as f:
            nw = int(f.readline())
            ids = [int(x) for x in f if x.strip()]
        assert len(ids) == nw
        radii = [(xyz[i][0]**2 + xyz[i][1]**2)**0.5 for i in ids]
        target = 0.5 * args.diameter
        tol = max(1.0e-6, 5.0e-3 * args.diameter)
        if max(abs(r-target) for r in radii) > tol:
            raise AssertionError(
                f"Cylinder_wall radius is not d/2: min={min(radii):.6g}, "
                f"max={max(radii):.6g}, expected={target:.6g}. "
                "Gmsh topological boundary-layer extrusion uses smoothed discrete normals; "
                "enable PROJECT_CYLINDER_WALL=1 (default) or inspect the generated wall."
            )

    print(f"[validate] OK nodes={nnode} tetra={len(tet)} prism={len(pri)}")


if __name__ == "__main__":
    main()
