#!/bin/bash

#mesh
#一方向分割数
e=$1
#解析領域の大きさ
ep=$2
np=$3

# 実行ディレクトリ
directory="result_fluid_sups_karman_vortex/FOM_${e}-${ep}-${np}"

cd solvers/fluid_sups/karman_vortex
#. run_karman_mixed.sh

# ------------------------------------------------------------
# Ahmed mesh
#
# MSH_FILE can be overridden from the environment, e.g.
#
#   MSH_FILE=./another_ahmed_mesh.msh \
#   . shell/execution/exec_fom_fluid_sups_mixed.sh
#
# Default keeps the current behavior.
# ------------------------------------------------------------
#MSH_FILE="${MSH_FILE:-./ahmed_groundprism_L1_current_prism_tet_groups_orientation_fixed.msh}"

MSH_FILE="${MSH_FILE:-./ahmed_groundprism_L3_surface5_prism4_inner3_outer6_body10_prism_tet_groups_orientation_fixed.msh}"
bash ./run_ahmed.sh --msh "$MSH_FILE"
#bash ./run_ahmed.sh --msh ./ahmed_groundprism_L3_finer_prism_tet_groups_orientation_fixed.msh

#. shell/meshgen_karman_vortex_2d.sh
cd ../../..

rm -rf "$directory"
mkdir -p "$directory"
cd "$directory"

# ------------------------------------------------------------
# Move preprocessed Ahmed mesh / BC files.
#
# IMPORTANT:
# D_bc_v.dat generated by run_ahmed.sh contains:
#   Inlet       : (U,0,0)
#   lowerWall   : (0,0,0) strong no-slip
#   upperWall   : uz=0
#   front/back  : uy=0
# Ahmed wall is NOT included because it is imposed by Nitsche.
# ------------------------------------------------------------
AHMED_MESH_DIR="../../solvers/fluid_sups/karman_vortex/mesh_ahmed_groundprism"

mv "$AHMED_MESH_DIR/graph.dat" ./
mv "$AHMED_MESH_DIR/node.dat" ./
mv "$AHMED_MESH_DIR/elem_prism.dat" ./
mv "$AHMED_MESH_DIR/elem_tet.dat" ./
mv "$AHMED_MESH_DIR/D_bc_v.dat" ./
mv "$AHMED_MESH_DIR/surf.dat" ./
mv "$AHMED_MESH_DIR/surf_prism.dat" ./
mv "$AHMED_MESH_DIR/surf_tet.dat" ./

# for parameteric study
rm -f cond.dat
./../../../test_thermal/bin/cmd2cond "#density_array" double 1 6.843575418900000e+04
mv cond.dat density.dat
./../../../test_thermal/bin/cmd2cond "#viscosity_array" double 1 1
mv cond.dat viscosity.dat

./../../../test_thermal/bin/cmd2cond "#target_density" double 1 6.843575418900000e+04
mv cond.dat target_density.dat
./../../../test_thermal/bin/cmd2cond "#target_viscosity" double 1 1
mv cond.dat target_viscosity.dat

./../../../test_thermal/bin/cmd2cond "#snapshot_interval" int 1 1 "#rom_finish_time" double 1 0.5 "#rom_output_interval" int 1 1000
mv cond.dat rom_cond.dat

./../../../test_thermal/bin/cmd2cond "#time_spacing" double 1 0.00005 "#output_interval" int 1 10  "#finish_time" double 1 0.5 "#mat_max_iter" int 1 10000 "#mat_epsilon" double 1 1.0e-8

./../../../../test_thermal/submodule/monolis/submodule/gedatsu/bin/gedatsu_nodal_graph_partitioner -n $np

#./../../utils/bin/elem2graph -ie surf.dat -og surf_graph.dat
#./../../../../test_thermal/submodule/monolis/submodule/gedatsu/bin/gedatsu_connectivity_graph_partitioner -n $np -i surf_graph.dat -ig graph.dat

./../../utils/bin/elem2graph -ie surf_prism.dat -og surf_prism_graph.dat
./../../../../test_thermal/submodule/monolis/submodule/gedatsu/bin/gedatsu_connectivity_graph_partitioner -n $np -i surf_prism_graph.dat -ig graph.dat

./../../utils/bin/elem2graph -ie surf_tet.dat -og surf_tet_graph.dat
./../../../../test_thermal/submodule/monolis/submodule/gedatsu/bin/gedatsu_connectivity_graph_partitioner -n $np -i surf_tet_graph.dat -ig graph.dat

./../../utils/bin/elem2graph -ie elem_prism.dat -og graph_elem_prism.dat
./../../utils/bin/elem2graph -ie elem_tet.dat -og graph_elem_tet.dat
./../../../../test_thermal/submodule/monolis/submodule/gedatsu/bin/gedatsu_connectivity_graph_partitioner -n $np -i graph_elem_tet.dat -ig graph.dat
./../../../../test_thermal/submodule/monolis/submodule/gedatsu/bin/gedatsu_connectivity_graph_partitioner -n $np -i graph_elem_prism.dat -ig graph.dat

python3 ./../../shell/mag/node2dist_val.py ./node.dat node_distval.dat ./graph.dat

# ------------------------------------------------------------
# DO NOT regenerate D_bc_v.dat here.
#
# The old line below was for the Karman coordinate-based BC and
# overwrote the correct Ahmed Physical-Group based BC:
#
# python3 ./../../shell/mag/make_karman_mixed_bc.py ./node.dat D_bc_v.dat
#
# Keep the D_bc_v.dat moved above from run_ahmed.sh.
# ------------------------------------------------------------
if [[ ! -f D_bc_v.dat ]]; then
    echo "ERROR: Ahmed D_bc_v.dat is missing." >&2
    exit 1
fi

echo "Ahmed D_bc_v.dat preserved from run_ahmed.sh"
echo -n "  header: "
head -n 1 D_bc_v.dat

./../../../../test_thermal/submodule/monolis/submodule/gedatsu/bin/gedatsu_dist_val_partitioner_R -n $np -i node_distval.dat -ig graph.dat

./../../../../test_thermal/submodule/monolis/submodule/gedatsu/bin/gedatsu_bc_partitioner_R -n $np -i D_bc_v.dat -ig graph.dat

for i in $(seq 0 $((np-1)))
do
    python3 ../../shell/mag/distval2node.py ./parted.0/node_distval.dat.$i  ./parted.0/node.dat.$i
done

cd ../..

